### ISSUE TITLE
[ADD] except-pass: New check to detect sentence "pass" in exceptions catched

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pylint-odoo#101]
```python
try:
  sentences
except:
  pass  # emit message
```

A good justification of this case is:
http://stackoverflow.com/a/21553825

This is a new guideline then

- [x] Add documentation creating PR to https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md in order to get feedback from community.
- [ ] Create a PR for pycqa/pylint to check if is a good idea for the maintainer
- [x] if is not good idea for pycqa/pylint then create it for vx/pylint-odoo
- [ ] After merge vx/pylint-odoo migrated to oca/pylint-odoo. https://github.com/Vauxoo/pylint-odoo/issues/106

**Comment by JesusZapata** [comment]
Done!
But it was rejected! https://github.com/PyCQA/pylint/pull/1261
The documentation in! https://github.com/OCA/maintainer-tools/pull/252

**Comment by JesusZapata** [comment]
@moylop260 I made a PR for third item of checklist https://github.com/Vauxoo/pylint-odoo/pull/106

**Comment by moylop260** [comment]
WIP from https://github.com/OCA/pylint-odoo/pull/107
