### ISSUE TITLE
[ADD] xpath-ref-string: Add check to validate a xpath referenced to string

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pylint-odoo#114]
If odoo use a xml view inherited with:
  - `<xpath expr="//page[@string='Other Information']">`
But using a translated instance then you will see a error for other language but for english will work fine!

Then we need a new lint check to avoid this case.

Thanks @oscarolar 
Reference https://github.com/Vauxoo/abastotal/pull/147/files

NOTE: The version 10.0 has this validation now.
TODO: If is a check for just one version maybe is not a good idea but I will let open this issue in order to discuss it

**Comment by luisg123v** [comment]
I think this issue may be closed now, as this validation is included in Odoo itself from a long time ago, which makes not possible to base xpaths on string attributes.
