### ISSUE TITLE
[IMP] Detected unnecesary attribute noupdate="0" into the odoo tag <odoo noupdate="0">

### ISSUE THREAD

**Issue by JesusZapata** [Vauxoo/pylint-odoo#119]
Detected unnecesary attribute `noupdate="0"` into the odoo tag `<odoo noupdate="0"> `

Related with this comment https://github.com/Vauxoo/pylint-odoo/pull/117#issuecomment-306526997

**Comment by luisg123v** [comment]
Closing since related PRs have been closed.
