### ISSUE TITLE
XML with noupdate="1" and noupdate="0"

### ISSUE THREAD

**Issue by alxolivares** [Vauxoo/pylint-odoo#128]
According to issue #116 the tag `<data>` is unnecessary and should be avoided, but in some cases we need something like this:

```xml
<odoo>
    <data noupdate="1">
        <record></record>
    </data>
    <record></record>
</odoo>
```
For this especial case we get the **[W7939(deprecated-data-xml-node), ]** error in travis.

Reference: https://github.com/Vauxoo/worldpromotionals/pull/270

Regards

**Comment by moylop260** [comment]
you need define 2 data nodes

**Comment by JesusZapata** [comment]
@alxolivares 
I made this PR https://github.com/Vauxoo/pylint-odoo/pull/129 to skip your case

As additional information, you can also make the following change in your code
```xml
<odoo>
    <data noupdate="1">
        <record></record>
    </data>
    <data noupdate="0">
        <record></record>
   </data>
</odoo>
```

**Comment by alxolivares** [comment]
@JesusZapata
Thanks for the feedback!
