### ISSUE TITLE
[REF] javascript-lint: Skip js of static/lib folder

### ISSUE THREAD

**Issue by moylop260** [Vauxoo/pylint-odoo#15]
Currently:
`app/__init__.py:1: [W7903(javascript-lint), ] static/lib/smartmenus/jquery.smartmenus.js:1180:6: Missing semicolon.`
`app/__init__.py:1: [W7903(javascript-lint), ] other.js:1180:6: Missing semicolon.`

Expected
<s>`app/__init__.py:1: [W7903(javascript-lint), ] static/lib/smartmenus/jquery.smartmenus.js:1180:6: Missing semicolon.`</s>
`app/__init__.py:1: [W7903(javascript-lint), ] other.js:1180:6: Missing semicolon.`

**Comment by moylop260** [comment]
@oscarolar Am I right?

**Comment by oscarolar** [comment]
This is great!
