### ISSUE TITLE
Version controller not detected while adding a new module 

### ISSUE THREAD

**Issue by umiphos** [Vauxoo/pylint-odoo#150]
**The problem**
A 10.0.1.0.0 was ser as a version of a module in a 11.0 branch, this is causing problems in the version of the odoo app installed.

**This is how we see it after installing the module.**
![image](https://user-images.githubusercontent.com/4094256/42393430-f906702c-811b-11e8-894f-204761f26f54.png)

**The module that is triggering all this**
https://git.vauxoo.com/vauxoo/mexico/blob/11.0/l10n_mx_edi_hr_expense/__manifest__.py#L6

**This was the work area where I acknowledged this error**
https://git.vauxoo.com/vauxoo/mexico/merge_requests/1247

**Comment by moylop260** [comment]
@luisg123v 
Could you help me to check it?
