### ISSUE TITLE
missing-manifest-dependency: don't take into account files within tests directory

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/pylint-odoo#154]
Since tests files are executed only when running tests, external dependencies defined on those files should not be required in the manifest as external Python dependencies. Those dependencies will not be used in a non-testing environment and, if tests are run and dependencies are not satisfied, the tests will fail anyway.

**Comment by luisg123v** [comment]
CC @moylop260

**Comment by moylop260** [comment]
First Create the patch for oca please

**Comment by luisg123v** [comment]
Roger, I like that approach.
