### ISSUE TITLE
Author error in test of modules that are not from vauxoo.

### ISSUE THREAD

**Issue by alan196** [Vauxoo/pylint-odoo#157]
# Steps to reproduce.

- Create a module and in the manifest put like author: "Jarsa Sistemas"
- Make a MR.

# Expected Behaviour

- If there is no other LINT error, pass the tests.

# Current Behaviour

- Get the following error `[C8101(manifest-required-author), ] Missing author required "Vauxoo" in manifest file`

I have this error in MR https://git.vauxoo.com/jarsa/tenoli/merge_requests/48/

**Comment by luisg123v** [comment]
@alan196  
This should be solved now. Could you check, please? I've got no access to your repo.

**Comment by alan196** [comment]
yes it works @luisg123v 👍 thanks
