### ISSUE TITLE
Future warning: use of specific tests will be required.

### ISSUE THREAD

**Issue by oscarolar** [Vauxoo/pylint-odoo#175]
While running Odoo in Python 3.8.2 found the following warning:

<img width="1281" alt="Screen Shot 2020-08-17 at 22 49 44" src="https://user-images.githubusercontent.com/3836433/90468630-8bbbf780-e0dc-11ea-94f1-56596cc48047.png">

Then I tried to fix it but the linter said no no no:

<img width="1360" alt="Screen Shot 2020-08-17 at 22 46 27" src="https://user-images.githubusercontent.com/3836433/90468665-9c6c6d80-e0dc-11ea-9e56-e877a47f229c.png">

Maybe now it isn't time worthy but it is good to have it under the radar.

**Comment by moylop260** [comment]
I don't think it is related with pylint-odoo but pylint

Please, feel free to re-open it if new versions reproduce it
