### ISSUE TITLE
Duplicate fields

### ISSUE THREAD

**Issue by imanie383** [Vauxoo/pylint-odoo#178]
We need a lint that validates duplicate fields, to avoid:
![image](https://user-images.githubusercontent.com/35231827/112076932-fc2e6980-8b40-11eb-8b95-612861a89214.png)

**Comment by imanie383** [comment]
@moylop260

**Comment by moylop260** [comment]
@antonag32 

In fact, it is done but it could require a fix
 - https://github.com/OCA/pylint-odoo/blob/043b4c596cf16c42ca96a91e410e85ff61247d11/pylint_odoo/checkers/modules_odoo.py#L823
 -

**Comment by antonag32** [comment]
@moylop260 I think we can  close this? XML files are no longer checked by pylint-odoo and we just did something [related to this in oca hooks](https://github.com/OCA/odoo-pre-commit-hooks/pull/58).

**Comment by moylop260** [comment]
Totally agree!

I just added the following XML code in the test_repo:

```xml
        <record id="view partner form inherit" model="ir.ui.view">
            <field name="name">res.partner.form.inherit</field>
            <field name="model">res.partner</field>
            <field name="priority" eval="30"/>
            <field name="inherit_id" ref="base.view_partner_form"/>
            <field name="priority" eval="100"/>
            <field name="arch" type="xml">
                <xpath expr="//button[@name='toggle active']" position="before">
                    <button class="o stat button" name="action open duplicates" type="object" icon="fa-clone" string="Show duplicates"/>
                    <button class="o stat button" name="action open similar" type="object" icon="fa-clone" string="Show similar"/>
                </xpath>
            </field>
        </record>
```

After run the unittest the result was:

`test_repo/broken_module/model_view_odoo2.xml:75 Duplicate xml field "priority" in lines 77 - [xml-duplicate-fields]`

<img width="781" alt="Screenshot 2022-11-09 at 14 51 44" src="https://user-images.githubusercontent.com/6644187/200939314-05db9d2e-488e-4b54-92d6-95d68e1d1b22.png">
