### ISSUE TITLE
Add new LINT check to avoid that unit test inherit produce repeated runs of the same unit test method

### ISSUE THREAD

**Issue by zaoral** [Vauxoo/pylint-odoo#63]
**Background**

When you inherit form a unit tests class it seams that the inherited class repeat the same unit test defined in the first class (repeat the `def test_xxx` methods)

``` python
from openerp.tests import common

Class A (common.TransactionCase):

   def helper()
   def helper_2()
   def other_thing_different_of_test()
   def test_a_01()
   def test_a_02()
   def test_a_03()
   def test_a_04()

Class B (A):

   def helper_3()
   def test_b_01()
   def test_b_02()
```

In the current example when we run the unit test using `odoo.py ...  --test-enable` we will found that the methods will be run twice as they are reported in the server log

``` diff
A.test_a_01
A.test_a_02
A.test_a_03
A.test_a_04
B.test_a_01 (repeated)
B.test_a_02 (repeated)
B.test_a_03 (repeated)
B.test_a_04 (repeated)
B.test_b_01
B.test_b_02
```

An real example of this situation can be reviewed in https://github.com/Vauxoo/yoytec/issues/1708

To avoid this we could manage two types of unit test class: one for the unit test common (helpers) and one for the unit test cases method itself.

NOTE: In the case that the `Class A` and `Clase B` are in different modules will gives the running of each test defined in `Class A` 3 times:
- first time for the module_A (were the method is originally defined in Class A)
- second time in the inherited unit test (module_B) as current class unit test (Class B)
- third time in the inherited unit test (module_B) marked as the super class unit test (Class A)

**Proposal**

In order to do not repeat unit test cases run in odoo server and get advantage of share common helpers between unit test in the same/different module I suggest create a new LINT that do not let us to inherit from a UnitTestClass if this one has unit test cases methods (def test\* kind). And, since we do not have the information about the class we are inheriting then a good point of compare could be: those classes inside `test.*.py` files can not have `def test*` and `def other_things` methods, should have only one kind of method: unit test case or helper

**Comment by luisg123v** [comment]
I consider this would be a lint very hard to implement, and I've never seen this case, at least not inheriting a class in the same module, which it's what I consider could feasible to implement.

Because of the above, I'm closing this issue.

CC @moylop260, feel free to correct me if I'm wrong.
