### ISSUE TITLE
[IMP] Add test to avoid 'string' field parameter being the same as field attribute name. Support old api

### ISSUE THREAD

**Issue by JesusZapata** [Vauxoo/pylint-odoo#99]
Check if the name of the variable is equal to string parameter. Support old api

**Tested cases**

`name_equal_to_string = fields.float("Name equal to string") # Show warning`
`many_2_one = fields.many2one('res.users', "Many 2 one") # Show warning`
`many_2_many = fields.many2many('res.users', 'relation', 'fk_column_from', 'fk_column_to', "Many 2 many") # Show warning`

**Comment by luistorresm** [comment]
Could you add the next test case please?

many_2_one_id = fields.many2one('res.users', "Many 2 one") # Show warning

**Comment by JesusZapata** [comment]
Yes no problem

**Comment by moylop260** [comment]
> `many_2_one_id = fields.many2one('res.users', "Many 2 one") # Show warning`

This case was implemented from master recently.
This could be other check (with other name and number) in other to choose when emit it.

**Comment by JesusZapata** [comment]
On the API 8 the Functionality of take the name of variable and used as string is not supported.

```
from openerp.osv import fields as old_fields
```
```
_columns = {
    'more_name' : old_fields.char()
}
```
Show 
![screenshot](https://cloud.githubusercontent.com/assets/1387970/21568720/2c406e68-ce8d-11e6-8fad-978980fd198f.jpg)
